### ISSUE TITLE
Filter bugg if there's just one element in filter like ( 'X','in',(Y))

### ISSUE THREAD

**Issue by AdriNicolau** [gisce/powerp-backend#23]
* Found a bugg in the file models.py where if the filter is an "in" of just one element array crash.
```python
            count = model.search_count(search_params)
            res_ids = model.search(search_params, limit=limit, offset=offset)
```
* Both methods search_count() and search() are the ones that crash. 
* The error is the following: 
```stack trace
{Fault}<Fault 'int' object has no attribute '__getitem__': 'Traceback (most recent call last):\n  
File "/home/anicolau/Projectes/erp/server/bin/netsvc.py", line 334, in dispatch\n    result = LocalService(service_name)(method, *params)\n  
File "/home/anicolau/Projectes/erp/server/bin/netsvc.py", line 87, in __call__\n    res = getattr(self, method)(*params)\n  
File "/home/anicolau/Projectes/erp/server/bin/service/web_services.py", line 583, in execute\n    res = service.execute(db, uid, object, method, *args)\n  
File "/home/anicolau/Projectes/erp/server/bin/osv/osv.py", line 61, in wrapper\n    return f(self, dbname, *args, **kwargs)\n  File "/home/anicolau/Projectes/erp/server/bin/osv/osv.py", line 126, in execute\n    res = pool.execute_cr(cr, uid, obj, method, *args, **kw)\n  
File "/home/anicolau/Projectes/erp/server/bin/osv/osv.py", line 117, in execute_cr\n    return getattr(object, method)(cr, uid, *args, **kw)\n  
File "/home/anicolau/Projectes/erp/server/bin/osv/orm.py", line 15...
```
* Is possible to trigger the bug with the following request:
```api
GET http://localhost/api/res.users?schema=last_location&filter=[('id','in',(1))]
```

**Comment by ecarreras** [comment]
This is because when you are doing `(1)` this is not a tuple, this is simple 1

```python
In [10]: type((1))
Out[10]: int

In [11]: type((1,))
Out[11]: tuple

In [12]: type([1])
Out[12]: list
```

**Comment by AdriNicolau** [comment]
Well, then it's not a bugg, its a programming error on the request. We can close this issue.

**Comment by ecarreras** [comment]
The best option is to use always array `[]` and not tuple `(,)`.
If you do the following request:
`GET http://localhost/api/res.users?schema=last_location&filter=[('id','in',[1])]` will work
